### PR TITLE
fix the eth balance decimal to 3 places

### LINKED ISSUE #310: Fix the decimal for eth balance

### PR DESCRIPTION
**Pull request by omsant02**
## Description

This pull request addresses issue #310 by limiting the ETH balance display to 3 decimal places.

### Changes made:
- Modified `CurrentEnv/index.tsx` to format the ETH balance display with exactly 3 decimal places
- Used `parseFloat(ethers.utils.formatEther()).toFixed(3)` to ensure consistent decimal formatting
- This improves readability of the balance display in the UI

The fix prevents displaying excessive decimal places when showing ETH balances, which was creating unnecessary visual noise in the interface.

### ScreenShot
image

### Related Issue
Fixes #310

### CODE REVIEW

**Review by varex83 — CHANGES_REQUESTED** [review]
I think we should check should how many decimal places to keep
image
in this case 1000.000 should be just 1000

**Comment by omsant02** [comment]
image
image
image


fixed it, but the issue still remains is the wallet balance is hardcoded, would solve it in a separate pr

File: plugin/src/components/CurrentEnv/index.tsx [hunk 1]
```diff
@@ -20,7 +20,9 @@ export const CurrentEnv: React.FC = () => {
 		env === "wallet"
 			? {
 				address: walletAccount?.address,
-				balance: 0
+				balance: walletAccount?.address != null
+					? ethers.BigNumber.from(2000000000000000)
```
Comment (varex83) [inline plugin/src/components/CurrentEnv/index.tsx:24]: Why do we set balance to this number?

**Review by varex83 — APPROVED** [review]
